---

- name: Install snapraid
  ansible.builtin.include_tasks:
    file: install_snapraid.yml

- name: Install snapper
  ansible.builtin.include_tasks:
    file: install_snapper.yml

- name: Install snapraid-btrfs
  ansible.builtin.include_tasks:
    file: install_snapraid_btrfs.yml

- name: Install snapraid-btrfs-runner
  ansible.builtin.include_tasks:
    file: install_snapraid_btrfs_runner.yml
