---
- name: Version check
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Run version check
      ansible.builtin.include_role:
        name: version_check

- name: Maintain MANS
  hosts: mans_host
  become: true
  gather_facts: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Check if operating system is Debian
      ansible.builtin.fail:
        msg: >
          This playbook is only supported on Debian.
          Disable this check by setting 'skip_os_check: true' in vars.yml.
      when:
        - ansible_distribution != "Debian"
        - not skip_os_check|default(false)|bool

  roles:
    - role: wipecheck

    - role: manage_linux

    - role: manage_zsh
      when: configure_zsh

    - role: stefangweichinger.ansible_rclone
      when: install_rclone

    - role: geerlingguy.docker
      when: install_docker or configure_scrutiny

    - role: install_mergerfs

    - role: install_snapraid

    - role: install_btrfs

    - role: manage_disks_nas

    - role: configure_mergerfs

    - role: configure_snapraid

    - role: vladgh.samba.server

    - role: muffins_cache_mover

    - role: docker_scrutiny
      when: configure_scrutiny
