---
- name: Maintain MANS
  hosts: mans-host
  become: true
  gather_facts: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Check if operating system is Debian
      ansible.builtin.fail:
        msg: >
          This playbook is only supported on Debian.
          Disable this check by setting 'skip_os_check: true' in vars.yml.
      when:
        - ansible_distribution != "Debian"
        - not skip_os_check|default(false)|bool

  tasks:
    - name: Run wipecheck role
      ansible.builtin.include_role:
        name: wipecheck

    - name: Run manage_linux role
      ansible.builtin.include_role:
        name: manage_linux

    - name: Run stefangweichinger.ansible_rclone role
      ansible.builtin.include_role:
        name: stefangweichinger.ansible_rclone
      when: install_rclone

    - name: Run geerlingguy.docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Run install_mergerfs role
      ansible.builtin.include_role:
        name: install_mergerfs

    - name: Run install_snapraid role
      ansible.builtin.include_role:
        name: install_snapraid

    - name: Run install_btrfs role
      ansible.builtin.include_role:
        name: install_btrfs

    - name: Run manage_disks_nas role
      ansible.builtin.include_role:
        name: manage_disks_nas

    - name: Run configure_mergerfs role
      ansible.builtin.include_role:
        name: configure_mergerfs

    - name: Run configure_snapraid role
      ansible.builtin.include_role:
        name: configure_snapraid

    - name: Deploy & Configure Samba
      ansible.builtin.include_role:
        name: vladgh.samba.server

    # - name: Run muffins_cache_mover role
    #   include_role:
    #     name: muffins_cache_mover

    - name: Run docker_scrutiny role
      ansible.builtin.include_role:
        name: docker_scrutiny
      when: configure_scrutiny
