---
- name: Version check
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Run version check
      ansible.builtin.include_role:
        name: version_check

- name: Maintain MANS
  hosts: mans_host
  become: true
  gather_facts: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Check if operating system is Debian
      ansible.builtin.fail:
        msg: >
          This playbook is only supported on Debian.
          Disable this check by setting 'skip_os_check: true' in vars.yml.
      when:
        - ansible_distribution != "Debian"
        - not skip_os_check|default(false)|bool

  roles:
    - role: validate_parity_config
      tags:
        - validate
        - parity
        - config

    - role: wipecheck
      tags: wipecheck

    - role: manage_linux
      tags:
        - manage_linux
        - base_setup

    - role: manage_zsh
      when: configure_zsh
      tags:
        - manage_zsh
        - base_setup

    - role: stefangweichinger.ansible_rclone
      when: install_rclone
      tags:
        - rclone
        - base_setup

    - role: geerlingguy.docker
      when: install_docker or configure_scrutiny
      tags:
        - docker
        - base_setup
        - scrutiny

    - role: install_mergerfs
      tags:
        - install_mergerfs
        - mergerfs

    - role: install_snapraid
      tags:
        - install_snapraid
        - snapraid

    - role: install_btrfs
      tags:
        - install_btrfs
        - btrfs

    - role: manage_disks_nas
      tags:
        - manage_disks
        - btrfs

    - role: configure_mergerfs
      tags:
        - configure_mergerfs
        - mergerfs

    - role: configure_snapraid
      tags:
        - configure_snapraid
        - snapraid

    - role: vladgh.samba.server
      tags: samba

    - role: muffins_cache_mover
      tags: cache_mover

    - role: docker_scrutiny
      when: configure_scrutiny
      tags:
        - scrutiny
        - docker

    - role: configure_hdidle
      tags: hdidle

  post_tasks:
    - name: Display SnapRAID Configuration Notices
      ansible.builtin.debug:
        msg: "{{ snapraid_warning_message }}"
      when: snapraid_warning_message is defined
      tags:
        - configure_snapraid
        - snapraid

    - name: Display Mount Cleanup Notices
      ansible.builtin.debug:
        msg: "{{ mount_cleanup_message }}"
      when: mount_cleanup_message is defined
      tags:
        - manage_disks
        - btrfs
