---
roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.4
  - name: geerlingguy.docker
    version: 7.8.0

collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.4.0
  - name: community.docker
    version: 4.8.2
  - name: vladgh.samba
    version: 3.5.4
