---
roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.5
  - name: geerlingguy.docker
    version: 8.0.0

collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 12.3.0
  - name: community.docker
    version: 5.0.6
  - name: vladgh.samba
    version: 3.5.5
