---
roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.2
  - name: geerlingguy.docker
    version: 7.4.7

collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.1.0
  - name: community.docker
    version: 4.6.1
  - name: vladgh.samba
    version: 3.5.1
