---
- name: Required packages
  ansible.builtin.package:
    name:
      - git
      - zsh
      - powerline
      - fonts-powerline
    state: present

- name: Set ZSH as default shell
  ansible.builtin.user:
    name: "{{ zsh_user }}"
    shell: /bin/zsh

- name: Download Oh My ZSH installer
  ansible.builtin.get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install-ohmyzsh.sh
    mode: '0755'
  ignore_errors: yes

- name: Check if Oh My ZSH is installed
  ansible.builtin.stat:
    path: /home/{{ zsh_user }}/.oh-my-zsh
  register: zsh_ohmyzsh_installed

- name: Install Oh My ZSH
  become_user: "{{ zsh_user }}"
  ansible.builtin.command: /tmp/install-ohmyzsh.sh --unattended
  when: not zsh_ohmyzsh_installed.stat.exists

- name: Install Oh My ZSH plugins and themes
  become_user: "{{ zsh_user }}"
  block:
    - name: Clone zsh-autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "/home/{{ zsh_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        version: master
        force: true

    - name: Clone zsh-syntax-highlighting
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: "/home/{{ zsh_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        version: master
        force: true

    - name: Clone Powerlevel10k
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k
        dest: "/home/{{ zsh_user }}/.oh-my-zsh/custom/themes/powerlevel10k"
        version: master
        force: true

    - name: Set Powerlevel10k as the default theme
      become_user: "{{ zsh_user }}"
      ansible.builtin.lineinfile:
        path: "/home/{{ zsh_user }}/.zshrc"
        regexp: '^ZSH_THEME=".*"'
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
        state: present

# - name: Add zsh history settings to ~/.zshrc
#   become_user: "{{ zsh_user }}"
#   ansible.builtin.blockinfile:
#     path: "/home/{{ zsh_user }}/.zshrc"
#     marker: "# ANSIBLE: Disable zsh history sharing"
#     insertafter: "# ANSIBLE: Disable zsh history sharing (end)"
#     block: |
#       # Disable sharing history between zsh sessions
#       setopt noincappendhistory
#       setopt nosharehistory
