---
- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Restart mergerfs-media-cache
  systemd:
    name: mergerfs-media-cache.service
    state: restarted

- name: Restart mergerfs-media-cold
  systemd:
    name: mergerfs-media-cold.service
    state: restarted