---
- name: Ensure mountpoint for media exists
  file:
    path: /mnt/media
    state: directory
    mode: '0775'

- name: Count items in cache_disks
  set_fact:
    cache_disks_count: "{{ cache_disks|length }}"

- name: Generate cache_mounts list
  set_fact:
    cache_mounts: "{{ cache_mounts|default([]) + ['/mnt/cache-disks/cache%02d' % (index + 1)] }}"
  loop: "{{ cache_disks }}"
  loop_control:
    index_var: index

- name: Deploy mergerfs media_cached systemd service
  template:
    src: mergerfs.cache_mount.j2
    dest: /etc/systemd/system/mergerfs-media-cache.service
  notify:
    - Reload systemd daemon

- name: Ensure mergerfs-media-cache service is enabled
  ansible.builtin.systemd:
    name: mergerfs-media-cache.service
    enabled: true
  notify: Restart mergerfs_media_cache

- name: Check if mergerfs-media-cache service is running
  ansible.builtin.shell: systemctl is-active mergerfs-media-cache.service
  register: cache_service_status
  ignore_errors: true
  changed_when: false

- name: Start mergerfs-media-cache service if not running
  ansible.builtin.systemd:
    name: mergerfs-media-cache.service
    state: started
  when: cache_service_status.rc != 0