---
- name: Stage Scrutiny
  ansible.builtin.include_tasks:
    file: stage.yml

- name: Configure Notifications
  ansible.builtin.include_tasks:
    file: notify.yml

- name: Deploy Scrutiny
  ansible.builtin.include_tasks:
    file: deploy.yml
