---
- name: Ensure parity mount points exist
  ansible.builtin.file:
    path: "{{ parity_mount_path }}/parity{{ '%02d' % (index + 1) }}"
    state: directory
  loop: "{{ parity_disks }}"
  loop_control:
    index_var: index

- name: Ensure parity mounts are present in fstab
  ansible.builtin.blockinfile:
    path: /etc/fstab
    block: "{{ lookup('template', 'parity_mounts.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PARITY DISK MOUNTS"
    create: true

- name: Mount parity disks
  ansible.builtin.mount:
    path: "{{ parity_mount_path }}/parity{{ '%02d' % (index + 1) }}"
    src: "{{ item }}"
    fstype: ext4
    opts: "{{ manage_disks_nas_ext4_mount_opts }}"
    state: mounted
  loop: "{{ parity_disks }}"
  loop_control:
    index_var: index

# Cache Disks
- name: Ensure cache disk mount points exist
  ansible.builtin.file:
    path: "{{ cache_mount_path }}/cache{{ '%02d' % (index + 1) }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "0770"
  loop: "{{ cache_disks_only }}"
  loop_control:
    index_var: index
  when: cache_disks_only | length > 0

- name: Ensure cache disk mounts are present in fstab
  ansible.builtin.blockinfile:
    path: /etc/fstab
    block: |
      {% for disk in cache_disks_only %}
      {{ disk }}  {{ cache_mount_path }}/cache{{ '%02d' % (loop.index) }}  ext4  {{ manage_disks_nas_ext4_mount_opts }}  0  0
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - CACHE DISK MOUNTS"
  when: cache_disks_only | length > 0

- name: Mount cache disks
  ansible.builtin.mount:
    path: "{{ cache_mount_path }}/cache{{ '%02d' % (index + 1) }}"
    src: "{{ item }}"
    fstype: ext4
    opts: "{{ manage_disks_nas_ext4_mount_opts }}"
    state: mounted
  loop: "{{ cache_disks_only }}"
  loop_control:
    index_var: index
  when: cache_disks_only | length > 0

- name: Set permissions on cache disk directories
  ansible.builtin.file:
    path: "{{ cache_mount_path }}/cache{{ '%02d' % (index + 1) }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "0770"
    recurse: yes
  loop: "{{ cache_disks_only }}"
  loop_control:
    index_var: index
  when: cache_disks_only | length > 0

# Cache Paths
- name: Ensure cache paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ media_group }}"
    mode: "0770"
  loop: "{{ cache_paths_only }}"
  when: cache_paths_only | length > 0
