---
- name: Add the GPG key for the repository
  ansible.builtin.apt_key:
    url: https://packagecloud.io/ookla/speedtest-cli/gpgkey
    state: present

- name: Add the repository to apt sources
  ansible.builtin.apt_repository:
    repo: deb https://packagecloud.io/ookla/speedtest-cli/ubuntu/ trusty main
    state: present
    filename: ookla_speedtest-cli.list
