---
- name: Ensure directories for snapraid.content files exist
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ user }}"
    group: root
    mode: '0755'
  loop: "{{ content_files }}"
  become: yes

- name: Generate SnapRAID configuration
  ansible.builtin.template:
    src: snapraid.j2
    dest: /etc/snapraid.conf
    owner: "{{ user }}"
    group: root
    mode: '0644'