---
- name: Delete all existing Snapper configs
  ansible.builtin.command:
    cmd: "sudo snapper delete-config {{ item }}"
  loop: "{{ snapper_configs.stdout_lines | default([]) }}"
  when: snapper_configs.stdout_lines | default([]) | length > 0
  ignore_errors: true

- name: Remove all .snapshots subvolumes
  ansible.builtin.command:
    cmd: "btrfs subvolume delete {{ data_mount_path }}/data{{ '%02d' % item }}/.snapshots"
  loop: "{{ range(1, data_disks | length + 1) | list }}"
  ignore_errors: true

- name: Ensure the base config is named 'default'
  ansible.builtin.copy:
    src: /usr/share/snapper/config-templates/default
    dest: /etc/snapper/configs/default
    mode: '0644'
    remote_src: true

- name: Ensure 'TIMELINE_CREATE="no"' in the 'default' Snapper configuration
  ansible.builtin.lineinfile:
    path: /etc/snapper/configs/default
    regexp: '^TIMELINE_CREATE='
    line: 'TIMELINE_CREATE="no"'

- name: Create Snapper configurations for data disks using 'default' as a template
  ansible.builtin.command:
    cmd: "sudo snapper -c data{{ '%02d' % item }} create-config -t default {{ data_mount_path }}/data{{ '%02d' % item }}"
  loop: "{{ range(1, data_disks | length + 1) | list }}"
  when:
    - data_disks is defined
    - data_disks | length > 0

- name: Ensure 'TIMELINE_CREATE="no"' in each data disk's Snapper configuration
  ansible.builtin.lineinfile:
    path: "/etc/snapper/configs/data{{ '%02d' % item }}"
    regexp: '^TIMELINE_CREATE='
    line: 'TIMELINE_CREATE="no"'
  loop: "{{ range(1, data_disks | length + 1) | list }}"
  when: data_disks is defined and data_disks | length > 0

# - name: Update SNAPPER_CONFIGS with generated configurations
#   ansible.builtin.lineinfile:
#     path: /etc/default/snapper
#     regexp: '^SNAPPER_CONFIGS='
#     line: 'SNAPPER_CONFIGS="{{ range(1, data_disks | length + 1) | map("format", "data%02d") | join(" ") }}"'
#   when: data_disks is defined and data_disks | length > 0

- name: Verify snapper configs
  ansible.builtin.command:
    cmd: "snapper list-configs"
  register: snapper_configs_new
  changed_when: false
