---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart mergerfs_media_cache
  ansible.builtin.systemd:
    name: mergerfs-media-cache.service
    state: restarted

- name: Restart mergerfs_media_cold
  ansible.builtin.systemd:
    name: mergerfsmedia-cold.service
    state: restarted

- name: Restart mergerfs_cache_disks
  ansible.builtin.systemd:
    name: mergerfs-cache-disks.service
    state: restarted

- name: Restart mergerfs_media_noncached
  ansible.builtin.systemd:
    name: mergerfs-media-noncached.service
    state: restarted