name: Lint MANS

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: debian-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint yamllint

    - name: Run linters
      run: |
        ansible-lint -c .ansible-lint .
        yamllint .
