name: Lint MANS

on:
  pull_request:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.8.1
        with:
          requirements_file: requirements.yml
          args: "--exclude=.dependencies/ --exclude=.ansible/ --exclude=roles/geerlingguy.* --exclude=roles/stefangweichinger.*"
