name: Lint MANS

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        # TODO: pin to version once >24.7.0 is released
        # See https://github.com/ansible/ansible-lint/discussions/4281
        uses: ansible/ansible-lint@main
        with:
          requirements_file: requirements.yml
