- name: Confirm disk wiping
  block:
    - ansible.builtin.pause:
        prompt: |
          You have set wipe_and_setup to true. This will wipe all non-compliant data/parity/cache disk vars.
          Are you sure you want to continue? (yes/no)
      register: wipe_confirmation

    - name: Validate user input
      ansible.builtin.fail:
        msg: "Invalid input. Please enter 'yes' or 'no'."
      when: wipe_confirmation.user_input not in ['yes', 'no']

    - name: Recap disk wiping confirmation
      debug:
        msg: "You have confirmed to proceed with disk wiping. All data on the non-compliant disks will be permanently erased."
      when: wipe_confirmation.user_input == 'yes'

    - name: Abort playbook if user does not confirm
      ansible.builtin.fail:
        msg: "Disk wiping not confirmed. Aborting playbook execution."
      when: wipe_confirmation.user_input != 'yes'
  when: wipe_and_setup